version: 1.0.{build}
image: Visual Studio 2015


clone_depth: 1

platform:
    - x64
    - Win32

configuration:
    - Unicode Release
    - Unicode Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    verbosity: minimal

build_script:
    - cd c:\projects\notepad-plus-plus\scintilla\win32
    - if "%configuration%"=="Unicode Debug" set scintilla_debug=DEBUG=1
    - if "%configuration%"=="Unicode Release" set scintilla_debug=
    - nmake NOBOOST=1 %scintilla_debug% -f scintilla.mak
    - cd c:\projects\notepad-plus-plus\PowerEditor\visual.net\
    - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
   - name: "Notepad++.$(platform).$(configuration).exe"
     path: \**\Notepad++.exe
   - name: "SciLexer.$env:PLATFORM.$env:CONFIGURATION.dll"
     path: scintilla\bin\SciLexer.dll
